import { Data } from './types';
import bcrypt from 'bcryptjs';

const data: Data = {
  headerMenus: [
    { name: 'Webstoryboy', href: '/' },
    { name: 'Tutorial', href: '/tutorial' },
    { name: 'Lecture', href: '/lecture' },
    { name: 'Reference', href: '/reference' },
    { name: 'Inspiration', href: '/inspiration' },
  ],
  adminMenus: [
    { name: 'Overview', href: '/admin/overview' },
    { name: 'Posts', href: '/admin/posts' },
    { name: 'Users', href: '/admin/users' },
    { name: 'Pages', href: '/admin/web-pages' },
    { name: 'Settings', href: '/admin/settings' },
  ],
  pagesTitle: [
    {
      category: 'tutorial',
      title: '튜토리얼',
      text: '실전 웹 디자인과 개발을 위한 알찬 튜토리얼을 만나보세요. 초보자부터 전문가까지 모두를 위한 맞춤형 학습 자료를 제공합니다.',
      desc: '이 웹사이트는 웹 디자인과 개발을 위한 다양한 튜토리얼을 제공합니다. 현재 UI/UX CSS 디자인과 GSAP 인터랙티브 애니메이션을 주제로 한 기초 및 심화 학습이 구성되어 있습니다. UI/UX CSS 디자인에서는 CSS의 주요 기법과 레이아웃 구성, 속성 활용, 로그인 페이지 디자인, CSS 애니메이션, 반응형 디자인, Flexbox, Grid 레이아웃 등 실무에서 자주 쓰이는 기술을 다룹니다. GSAP 인터랙티브 애니메이션에서는 패럴랙스 기법, JavaScript 애니메이션, GSAP, Framer Motion, 스크롤 애니메이션, SVG 애니메이션 등 최신 트렌드의 인터랙티브 효과 구현법을 익힐 수 있습니다.',
      href: '/tutorial',
      subject: ['UI/UX CSS Design', 'GSAP Interative Animation'],
    },
    {
      category: 'lecture',
      title: '강의',
      text: '유료와 무료 강의를 통해 웹스토리보이의 깊이 있는 지식을 경험해보세요. 단계별 가이드로 쉽게 배울 수 있습니다.',
      desc: '웹스토리보이가 제공하는 유료 및 무료 강의에 대한 가이드를 제공합니다. 현재는 웹디자인개발기능사 2025와 리액트를 위한 자바스크립트 기초 마스터 강의가 준비되어 있으며, 유튜브 및 인프런에서 수강할 수 있습니다.웹디자인개발기능사 2025 강의는 2025년 시험 대비를 위한 실기 내용을 다룹니다. 이 강의는 기초 이론에서 실전까지, 시험에 필요한 웹디자인 및 개발 지식을 체계적으로 쌓을 수 있도록 돕습니다.리액트를 위한 자바스크립트 기초 마스터 리액트를 본격적으로 배우기 전, 필수 자바스크립트 개념과 기초 문법을 이해하도록 설계되었습니다. 이 강의를 통해 리액트 개발에 필요한 기본기를 단단히 다질 수 있습니다.',
      href: '/lecture',
      subject: [
        '웹디자인개발기능사 2025',
        '리액트를 위한 자바스크립트 기초 마스터',
      ],
    },
    {
      category: 'reference',
      title: '레퍼런스',
      text: '웹 디자인과 개발에 유용한 자료와 정보를 모았습니다. 작업에 꼭 필요한 레퍼런스를 확인해보세요.',
      desc: '웹스토리보이가 제공하는 유료 및 무료 강의에 대한 가이드를 제공합니다. 현재는 웹디자인개발기능사 2025와 리액트를 위한 자바스크립트 기초 마스터 강의가 준비되어 있으며, 유튜브 및 인프런에서 수강할 수 있습니다.웹디자인개발기능사 2025 강의는 2025년 시험 대비를 위한 실기 내용을 다룹니다. 이 강의는 기초 이론에서 실전까지, 시험에 필요한 웹디자인 및 개발 지식을 체계적으로 쌓을 수 있도록 돕습니다.리액트를 위한 자바스크립트 기초 마스터 리액트를 본격적으로 배우기 전, 필수 자바스크립트 개념과 기초 문법을 이해하도록 설계되었습니다. 이 강의를 통해 리액트 개발에 필요한 기본기를 단단히 다질 수 있습니다',
      href: '/reference',
      subject: ['HTML 레퍼런스', 'CSS 레퍼런스', 'JAVASCRIPT 레퍼런스'],
    },
    {
      category: 'inspiration',
      title: '인스퍼레이션',
      text: '독창적이고 창의적인 웹사이트들로 아이디어를 확장해보세요. 감각적인 디자인과 혁신적인 접근법이 가득합니다.',
      desc: '독창적이고 창의적인 아이디어가 가득한 특별한 웹사이트들을 엄선했습니다. 디자인과 창의성의 새로운 지평을 여는 이 컬렉션을 통해 신선한 영감을 얻어보세요. 당신의 상상력에 불을 붙일 특별한 작품들이 기다리고 있습니다!',
      href: '/inspiration',
      subject: ['SITE 인스퍼레이션'],
    },
  ],
  posts: [
    {
      title: 'Node.js로 서버 사이드 렌더링 구현하고 배포하기',
      slug: 'nodejs로-서버-사이드-렌더링-구현',
      category: 'inspiration',
      subCategory: 'SITE 인스퍼레이션',
      images: ['/images/post-1-1.jpg', '/images/post-1-2.jpg'],
      tags: ['site', 'React', 'gsap'],
      description: '개발 초보자와 전문가 모두를 위한 리소스를 제공합니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 27,
      numViews: 377,
      numLikes: 498,
      reviews: [],
    },
    {
      title: 'React와 GSAP로 인터랙티브 컴포넌트 구현하고 적용하기',
      slug: 'react와-gsap로-인터랙티브-컴포넌트-구현',
      category: 'inspiration',
      subCategory: 'SITE 인스퍼레이션',
      images: ['/images/post-2-1.jpg', '/images/post-2-2.jpg'],
      tags: ['Three.js', 'css'],
      description: '개발 초보자와 전문가 모두를 위한 리소스를 제공합니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 38,
      numViews: 880,
      numLikes: 180,
      reviews: [],
    },
    {
      title: 'Next.js에서의 정적 사이트 생성하고 비교하기',
      slug: 'nextjs에서의-정적-사이트-생성',
      category: 'tutorial',
      subCategory: 'UI/UX CSS Design',
      images: ['/images/post-5-1.jpg', '/images/post-5-2.jpg'],
      tags: ['ui/ux', 'Next.js', 'static site'],
      description: 'Next.js를 이용한 SEO 최적화.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 22,
      numViews: 340,
      numLikes: 120,
      reviews: [],
    },
    {
      title: 'GSAP ScrollTrigger로 스크롤 애니메이션 구현 및 배포하기',
      slug: 'gsap-scrolltrigger로-스크롤-애니메이션',
      category: 'inspiration',
      subCategory: 'SITE 인스퍼레이션',
      images: ['/images/post-6-1.jpg', '/images/post-6-2.jpg'],
      tags: ['GSAP', 'animation'],
      description: '스크롤 이벤트를 활용한 인터랙션.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 30,
      numViews: 500,
      numLikes: 230,
      reviews: [],
    },
    {
      title: 'JavaScript ES6로 모듈화 적용 및 배포하기',
      slug: 'javascript-es6로-모듈화-배우기',
      category: 'tutorial',
      subCategory: 'UI/UX CSS Design',
      images: ['/images/post-7-1.jpg', '/images/post-7-2.jpg'],
      tags: ['ui/ux', 'JavaScript', 'ES6'],
      description: 'JavaScript의 모듈 시스템 소개.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 16,
      numViews: 250,
      numLikes: 98,
      reviews: [],
    },
    {
      title: 'TypeScript로 안전한 코드 작성 및 요령 익히기',
      slug: 'typescript로-안전한-코드-작성',
      category: 'tutorial',
      subCategory: 'UI/UX CSS Design',
      images: ['/images/post-8-1.jpg', '/images/post-8-2.jpg'],
      tags: ['ui/ux', 'TypeScript', 'coding'],
      description: '타입 안정성을 강화한 코드 작성 방법.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 20,
      numViews: 360,
      numLikes: 180,
      reviews: [],
    },
    {
      title: 'React Context API 완전 정복하고 리덕스와 차이점 구별하기',
      slug: 'react-context-api-완전-정복',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-9-1.jpg', '/images/post-9-2.jpg'],
      tags: ['GSAP', 'React', 'Context API'],
      description: '전역 상태 관리에 대한 자세한 설명.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 40,
      numViews: 780,
      numLikes: 300,
      reviews: [],
    },
    {
      title: 'CSS Flexbox로 반응형 디자인 구현 및 적용해보기',
      slug: 'css-flexbox로-반응형-디자인-구현',
      category: 'reference',
      subCategory: 'HTML 레퍼런스',
      images: ['/images/post-10-1.jpg', '/images/post-10-2.jpg'],
      tags: ['CSS', 'Flexbox'],
      description: '유연한 레이아웃을 위한 Flexbox 사용법.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 18,
      numViews: 290,
      numLikes: 130,
      reviews: [],
    },
    {
      title: 'Webpack으로 번들링 최적화하고 리액트랑 비교하기',
      slug: 'webpack으로-번들링-최적화',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-11-1.jpg', '/images/post-11-2.jpg'],
      tags: ['GSAP', 'Webpack', 'bundling'],
      description: 'Webpack으로 번들링을 최적화하는 방법.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 24,
      numViews: 390,
      numLikes: 220,
      reviews: [],
    },
    {
      title: 'Three.js로 3D 오브젝트 만들기고 블렌더를 이용하기',
      slug: 'threejs로-3d-오브젝트-만들기',
      category: 'inspiration',
      subCategory: 'SITE 인스퍼레이션',
      images: ['/images/post-12-1.jpg', '/images/post-12-2.jpg'],
      tags: ['Three.js', '3D'],
      description: '3D 렌더링을 위한 기본 가이드.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 15,
      numViews: 280,
      numLikes: 105,
      reviews: [],
    },
    {
      title: 'Next.js API Routes 활용하기 리액트와 비교하기',
      slug: 'nextjs-api-routes-활용하기',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-13-1.jpg', '/images/post-13-2.jpg'],
      tags: ['GSAP', 'Next.js', 'API'],
      description: 'API Routes로 서버리스 함수 구현.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 10,
      numViews: 200,
      numLikes: 90,
      reviews: [],
    },
    {
      title: 'PWA로 오프라인 앱 개발하기 하지만 이제는 배용 적용하기',
      slug: 'pwa로-오프라인-앱-개발하기',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-14-1.jpg', '/images/post-14-2.jpg'],
      tags: ['GSAP', 'PWA', 'offline'],
      description: '프로그레시브 웹 앱 기본 가이드.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 14,
      numViews: 220,
      numLikes: 100,
      reviews: [],
    },
    {
      title: 'HTML5 Canvas로 드로잉 앱 만들기 테트리스도 만들어 보기',
      slug: 'html5-canvas로-드로잉-앱-만들기',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-15-1.jpg', '/images/post-15-2.jpg'],
      tags: ['GSAP', 'HTML5', 'Canvas'],
      description: 'Canvas를 활용한 드로잉 애플리케이션.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 19,
      numViews: 310,
      numLikes: 140,
      reviews: [],
    },
    {
      title: 'GraphQL로 데이터 효율적으로 가져오기 및 실제로 적용하기',
      slug: 'graphql로-데이터-효율적으로-가져오기',
      category: 'reference',
      subCategory: 'HTML 레퍼런스',
      images: ['/images/post-16-1.jpg', '/images/post-16-2.jpg'],
      tags: ['HTML', 'GraphQL', 'data'],
      description: 'GraphQL의 장점과 활용 사례.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 25,
      numViews: 400,
      numLikes: 210,
      reviews: [],
    },
    {
      title: 'Python으로 웹 크롤러 만들기고 뮤직 데이터 가져오기',
      slug: 'python으로-웹-크롤러-만들기',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-17-1.jpg', '/images/post-17-2.jpg'],
      tags: ['GSAP', 'Python', 'crawler'],
      description:
        'Python을 이용하여 넷플릭스 데이터를 수집하여 사이트를 구성합니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 35,
      numViews: 600,
      numLikes: 290,
      reviews: [],
    },
    {
      title: 'React와 Redux로 상태 관리 완벽 이해하고 써보기',
      slug: 'react와-redux로-상태-관리-완벽-이해',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-18-1.jpg', '/images/post-18-2.jpg'],
      tags: ['GSAP', 'React', 'Redux'],
      description: 'Redux를 이용한 전역 상태 관리.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 28,
      numViews: 450,
      numLikes: 230,
      reviews: [],
    },
    {
      title: 'Tailwind CSS로 반응형 디자인 적용 및 차이점 이해하기',
      slug: 'tailwind-css로-반응형-디자인',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-19-1.jpg', '/images/post-19-2.jpg'],
      tags: ['GSAP', 'Tailwind CSS', 'design'],
      description: 'Tailwind CSS의 장점과 활용법.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 20,
      numViews: 340,
      numLikes: 160,
      reviews: [],
    },
    {
      title: 'Rust 언어로 고성능 애플리케이션 개발 및 배포하기',
      slug: 'rust-언어로-고성능-애플리케이션-개발',
      category: 'inspiration',
      subCategory: 'SITE 인스퍼레이션',
      images: ['/images/post-20-1.jpg', '/images/post-20-2.jpg'],
      tags: ['SITE', 'Rust', 'performance'],
      description: 'Rust 언어의 특성과 활용 사례.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 18,
      numViews: 310,
      numLikes: 150,
      reviews: [],
    },
    {
      title: 'Rust 언어로 고성능 애플리케이션 개발하고 삭제하기',
      slug: 'rust-언어로-고성능-애플리',
      category: 'lecture',
      subCategory: '웹디자인개발기능사 2025',
      images: ['/images/post-20-1.jpg', '/images/post-20-2.jpg'],
      tags: ['Rust', 'performance'],
      description: 'Rust 언어의 특성과 활용 사례.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 18,
      numViews: 310,
      numLikes: 150,
      reviews: [],
    },
  ],
  users: [
    {
      name: 'John',
      password: bcrypt.hashSync('123456', 10),
      email: 'admin@example.com',
      emailVerified: false,
      image: '/images/face01.jpg',
      role: 'Admin',
      visitCount: 4,
    },
    {
      name: 'Jane Smith',
      password: bcrypt.hashSync('123456', 10),
      email: 'janesmith@example.com',
      emailVerified: false,
      image: '/images/face02.jpg',
      role: 'User',
      visitCount: 5,
    },
    {
      name: 'Alice Johnson',
      password: bcrypt.hashSync('123456', 10),
      email: 'alicej@example.com',
      emailVerified: false,
      image: '/images/face03.jpg',
      role: 'User',
      visitCount: 15,
    },
    {
      name: 'Bob Williams',
      password: bcrypt.hashSync('123456', 10),
      email: 'bobw@example.com',
      emailVerified: false,
      image: '/images/face04.jpg',
      role: 'User',
      visitCount: 8,
    },
    {
      name: 'Charlie Brown',
      password: bcrypt.hashSync('123456', 10),
      email: 'charlieb@example.com',
      emailVerified: false,
      image: '/images/face05.jpg',
      role: 'User',
      visitCount: 12,
    },
    {
      name: 'David Clark',
      password: bcrypt.hashSync('123456', 10),
      email: 'davidc@example.com',
      emailVerified: false,
      image: '/images/face06.jpg',
      role: 'User',
      visitCount: 3,
    },
    {
      name: 'Emma White',
      password: bcrypt.hashSync('123456', 10),
      email: 'emmaw@example.com',
      emailVerified: false,
      image: '/images/face07.jpg',
      role: 'User',
      visitCount: 9,
    },
    {
      name: 'Frank Green',
      password: bcrypt.hashSync('123456', 10),
      email: 'frankg@example.com',
      emailVerified: true,
      image: '/images/face08.jpg',
      role: 'User',
      visitCount: 14,
    },
    {
      name: 'Grace Hall',
      password: bcrypt.hashSync('123456', 10),
      email: 'graceh@example.com',
      emailVerified: false,
      image: '/images/face09.jpg',
      role: 'User',
      visitCount: 6,
    },
    {
      name: 'Henry Young',
      password: bcrypt.hashSync('123456', 10),
      email: 'henryy@example.com',
      emailVerified: true,
      image: '/images/face10.jpg',
      role: 'User',
      visitCount: 7,
    },
    {
      name: 'Isabella Lee',
      password: bcrypt.hashSync('123456', 10),
      email: 'isabellal@example.com',
      emailVerified: false,
      image: '/images/face01.jpg',
      role: 'User',
      visitCount: 11,
    },
    {
      name: 'Jack Wilson',
      password: bcrypt.hashSync('123456', 10),
      email: 'jackw@example.com',
      emailVerified: false,
      image: '/images/face02.jpg',
      role: 'User',
      visitCount: 13,
    },
    {
      name: 'Katherine Adams',
      password: bcrypt.hashSync('123456', 10),
      email: 'katherinea@example.com',
      emailVerified: false,
      image: '/images/face03.jpg',
      role: 'User',
      visitCount: 2,
    },
    {
      name: 'Leo Thomas',
      password: bcrypt.hashSync('123456', 10),
      email: 'leot@example.com',
      emailVerified: true,
      image: '/images/face04.jpg',
      role: 'User',
      visitCount: 4,
    },
    {
      name: 'Mia Scott',
      password: bcrypt.hashSync('123456', 10),
      email: 'mias@example.com',
      emailVerified: false,
      image: '/images/face05.jpg',
      role: 'User',
      visitCount: 16,
    },
    {
      name: 'Nathan Evans',
      password: bcrypt.hashSync('123456', 10),
      email: 'nathane@example.com',
      emailVerified: false,
      image: '/images/face06.jpg',
      role: 'User',
      visitCount: 1,
    },
    {
      name: 'Olivia Harris',
      password: bcrypt.hashSync('123456', 10),
      email: 'oliviah@example.com',
      emailVerified: false,
      image: '/images/face07.jpg',
      role: 'User',
      visitCount: 18,
    },
    {
      name: 'Paul Martin',
      password: bcrypt.hashSync('123456', 10),
      email: 'paulm@example.com',
      emailVerified: false,
      image: '/images/face08.jpg',
      role: 'User',
      visitCount: 17,
    },
    {
      name: 'Quinn Lewis',
      password: bcrypt.hashSync('123456', 10),
      email: 'quinnl@example.com',
      emailVerified: false,
      image: '/images/face09.jpg',
      role: 'User',
      visitCount: 20,
    },
    {
      name: 'Rachel Walker',
      password: bcrypt.hashSync('123456', 10),
      email: 'rachelw@example.com',
      emailVerified: false,
      image: '/images/face01.jpg',
      role: 'User',
      visitCount: 19,
    },
  ],
};

export default data;
