import { Data } from './types';
import bcrypt from 'bcryptjs';

const data: Data = {
  headerMenus: [
    { name: 'Webstoryboy', href: '/' },
    { name: 'Tutorial', href: '/tutorial' },
    { name: 'Lecture', href: '/lecture' },
    { name: 'Reference', href: '/reference' },
    { name: 'Inspiration', href: '/inspiration' },
  ],
  adminMenus: [
    { name: 'Overview', href: '/admin/overview' },
    { name: 'Posts', href: '/admin/posts' },
    { name: 'Users', href: '/admin/users' },
    { name: 'Pages', href: '/admin/web-pages' },
    { name: 'Settings', href: '/admin/settings' },
  ],
  pagesTitle: [
    {
      category: 'tutorial',
      title: '튜토리얼',
      text: '실무에서 바로 적용할 수 있는 웹 디자인과 개발 기술을 배워보세요. 초보자부터 전문가까지 모두를 위한 단계별 학습 자료를 제공합니다.',
      desc: '이 섹션은 실전 웹 디자인과 개발을 위한 다양한 튜토리얼을 제공합니다. CSS 디자인과 GSAP 인터랙티브 애니메이션을 중심으로 구성되어 있으며, CSS를 활용한 UI/UX 디자인 기법부터 최신 애니메이션 기술까지 학습할 수 있습니다. 실무에 바로 활용할 수 있는 기초 및 심화 지식을 제공하여, 웹 개발 능력을 한 단계 끌어올릴 수 있습니다.',
      href: '/tutorial',
      subjects: [
        {
          title: 'UI/UX CSS Design',
          href: 'uiux',
        },
        {
          title: 'GSAP Interative Animation',
          href: 'gsap',
        },
      ],
    },
    {
      category: 'lecture',
      title: '강의',
      text: '전문가의 노하우가 담긴 유료 및 무료 강의를 통해 새로운 기술을 배우고 성장해보세요.',
      desc: '이 섹션은 웹스토리보이가 제공하는 다양한 강의를 소개합니다. 웹디자인개발기능사 2025 시험 대비 강의와 리액트를 위한 자바스크립트 기초 강의가 준비되어 있으며, 실무 중심의 지식과 문제 해결 능력을 키울 수 있습니다. 초보자를 위한 기초 강의부터 전문가를 위한 심화 강의까지 모두 포함되어 있습니다.',
      href: '/lecture',
      subjects: [
        {
          title: '웹디자인개발기능사 2025',
          href: 'webdesign',
        },
        {
          title: '리액트를 위한 자바스크립트 기초 마스터',
          href: 'react+javascript',
        },
      ],
    },
    {
      category: 'reference',
      title: '레퍼런스',
      text: '웹 개발자와 디자이너를 위한 필수 레퍼런스를 확인하고 실무에서 활용하세요.',
      desc: 'HTML, CSS, 자바스크립트와 같은 기본 웹 기술부터 최신 트렌드까지 다양한 정보를 제공합니다. 이 섹션은 웹 개발 및 디자인 과정에서 자주 필요한 기술 자료와 팁을 한 곳에 모아 제공합니다. 실무에서 시간을 절약하고 효율적인 작업을 할 수 있도록 돕는 최고의 레퍼런스입니다.',
      href: '/reference',
      subjects: [
        {
          title: 'HTML 레퍼런스',
          href: 'html',
        },
        {
          title: 'CSS 레퍼런스',
          href: 'css',
        },
        {
          title: 'JAVASCRIPT 레퍼런스',
          href: 'javascript',
        },
      ],
    },
    {
      category: 'inspiration',
      title: '인스퍼레이션',
      text: '독창적이고 창의적인 웹사이트 컬렉션으로 새로운 아이디어를 발견하세요.',
      desc: '이 섹션은 독창적이고 감각적인 웹사이트 디자인을 소개합니다. 최신 디자인 트렌드와 창의적인 레이아웃, 혁신적인 인터랙션을 경험하며 여러분의 창작 활동에 영감을 불어넣어줄 것입니다. 디자이너와 개발자 모두에게 새로운 시각적 가능성을 제공합니다.',
      href: '/inspiration',
      subjects: [
        {
          title: 'SITE 인스퍼레이션',
          href: 'site',
        },
      ],
    },
  ],
  posts: [
    {
      title: 'Node.js로 서버 사이드 렌더링 구현하고 배포하기',
      slug: 'nodejs로-서버-사이드-렌더링-구현',
      category: 'inspiration',
      subCategory: 'SITE 인스퍼레이션',
      images: ['/images/post-1-1.jpg', '/images/post-1-2.jpg'],
      tags: ['site', 'React', 'gsap'],
      description: '개발 초보자와 전문가 모두를 위한 리소스를 제공합니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 27,
      numViews: 377,
      numLikes: 498,
      reviews: [],
    },
    {
      title: 'React와 GSAP로 인터랙티브 컴포넌트 구현하고 적용하기',
      slug: 'react와-gsap로-인터랙티브-컴포넌트-구현',
      category: 'inspiration',
      subCategory: 'SITE 인스퍼레이션',
      images: ['/images/post-2-1.jpg', '/images/post-2-2.jpg'],
      tags: ['Three.js', 'css'],
      description: '개발 초보자와 전문가 모두를 위한 리소스를 제공합니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 38,
      numViews: 880,
      numLikes: 180,
      reviews: [],
    },
    {
      title: 'Next.js에서의 정적 사이트 생성하고 비교하기',
      slug: 'nextjs에서의-정적-사이트-생성',
      category: 'tutorial',
      subCategory: 'UI/UX CSS Design',
      images: ['/images/post-5-1.jpg', '/images/post-5-2.jpg'],
      tags: ['ui/ux', 'Next.js', 'static site'],
      description: 'Next.js를 이용한 SEO 최적화.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 22,
      numViews: 340,
      numLikes: 120,
      reviews: [],
    },
    {
      title: 'GSAP ScrollTrigger로 스크롤 애니메이션 구현 및 배포하기',
      slug: 'gsap-scrolltrigger로-스크롤-애니메이션',
      category: 'inspiration',
      subCategory: 'SITE 인스퍼레이션',
      images: ['/images/post-6-1.jpg', '/images/post-6-2.jpg'],
      tags: ['GSAP', 'animation'],
      description: '스크롤 이벤트를 활용한 인터랙션.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 30,
      numViews: 500,
      numLikes: 230,
      reviews: [],
    },
    {
      title: 'JavaScript ES6로 모듈화 적용 및 배포하기',
      slug: 'javascript-es6로-모듈화-배우기',
      category: 'tutorial',
      subCategory: 'UI/UX CSS Design',
      images: ['/images/post-7-1.jpg', '/images/post-7-2.jpg'],
      tags: ['ui/ux', 'JavaScript', 'ES6'],
      description: 'JavaScript의 모듈 시스템 소개.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 16,
      numViews: 250,
      numLikes: 98,
      reviews: [],
    },
    {
      title: 'TypeScript로 안전한 코드 작성 및 요령 익히기',
      slug: 'typescript로-안전한-코드-작성',
      category: 'tutorial',
      subCategory: 'UI/UX CSS Design',
      images: ['/images/post-8-1.jpg', '/images/post-8-2.jpg'],
      tags: ['ui/ux', 'TypeScript', 'coding'],
      description: '타입 안정성을 강화한 코드 작성 방법.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 20,
      numViews: 360,
      numLikes: 180,
      reviews: [],
    },
    {
      title: 'React Context API 완전 정복하고 리덕스와 차이점 구별하기',
      slug: 'react-context-api-완전-정복',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-9-1.jpg', '/images/post-9-2.jpg'],
      tags: ['GSAP', 'React', 'Context API'],
      description: '전역 상태 관리에 대한 자세한 설명.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 40,
      numViews: 780,
      numLikes: 300,
      reviews: [],
    },
    {
      title: 'CSS Flexbox로 반응형 디자인 구현 및 적용해보기',
      slug: 'css-flexbox로-반응형-디자인-구현',
      category: 'reference',
      subCategory: 'HTML 레퍼런스',
      images: ['/images/post-10-1.jpg', '/images/post-10-2.jpg'],
      tags: ['CSS', 'Flexbox'],
      description: '유연한 레이아웃을 위한 Flexbox 사용법.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 18,
      numViews: 290,
      numLikes: 130,
      reviews: [],
    },
    {
      title: 'Webpack으로 번들링 최적화하고 리액트랑 비교하기',
      slug: 'webpack으로-번들링-최적화',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-11-1.jpg', '/images/post-11-2.jpg'],
      tags: ['GSAP', 'Webpack', 'bundling'],
      description: 'Webpack으로 번들링을 최적화하는 방법.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 24,
      numViews: 390,
      numLikes: 220,
      reviews: [],
    },
    {
      title: 'Three.js로 3D 오브젝트 만들기고 블렌더를 이용하기',
      slug: 'threejs로-3d-오브젝트-만들기',
      category: 'inspiration',
      subCategory: 'SITE 인스퍼레이션',
      images: ['/images/post-12-1.jpg', '/images/post-12-2.jpg'],
      tags: ['Three.js', '3D'],
      description: '3D 렌더링을 위한 기본 가이드.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 15,
      numViews: 280,
      numLikes: 105,
      reviews: [],
    },
    {
      title: 'Next.js API Routes 활용하기 리액트와 비교하기',
      slug: 'nextjs-api-routes-활용하기',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-13-1.jpg', '/images/post-13-2.jpg'],
      tags: ['GSAP', 'Next.js', 'API'],
      description: 'API Routes로 서버리스 함수 구현.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 10,
      numViews: 200,
      numLikes: 90,
      reviews: [],
    },
    {
      title: 'PWA로 오프라인 앱 개발하기 하지만 이제는 배용 적용하기',
      slug: 'pwa로-오프라인-앱-개발하기',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-14-1.jpg', '/images/post-14-2.jpg'],
      tags: ['GSAP', 'PWA', 'offline'],
      description: '프로그레시브 웹 앱 기본 가이드.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 14,
      numViews: 220,
      numLikes: 100,
      reviews: [],
    },
    {
      title: 'HTML5 Canvas로 드로잉 앱 만들기 테트리스도 만들어 보기',
      slug: 'html5-canvas로-드로잉-앱-만들기',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-15-1.jpg', '/images/post-15-2.jpg'],
      tags: ['GSAP', 'HTML5', 'Canvas'],
      description: 'Canvas를 활용한 드로잉 애플리케이션.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 19,
      numViews: 310,
      numLikes: 140,
      reviews: [],
    },
    {
      title: 'GraphQL로 데이터 효율적으로 가져오기 및 실제로 적용하기',
      slug: 'graphql로-데이터-효율적으로-가져오기',
      category: 'reference',
      subCategory: 'HTML 레퍼런스',
      images: ['/images/post-16-1.jpg', '/images/post-16-2.jpg'],
      tags: ['HTML', 'GraphQL', 'data'],
      description: 'GraphQL의 장점과 활용 사례.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 25,
      numViews: 400,
      numLikes: 210,
      reviews: [],
    },
    {
      title: 'Python으로 웹 크롤러 만들기고 뮤직 데이터 가져오기',
      slug: 'python으로-웹-크롤러-만들기',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-17-1.jpg', '/images/post-17-2.jpg'],
      tags: ['GSAP', 'Python', 'crawler'],
      description:
        'Python을 이용하여 넷플릭스 데이터를 수집하여 사이트를 구성합니다.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 35,
      numViews: 600,
      numLikes: 290,
      reviews: [],
    },
    {
      title: 'React와 Redux로 상태 관리 완벽 이해하고 써보기',
      slug: 'react와-redux로-상태-관리-완벽-이해',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-18-1.jpg', '/images/post-18-2.jpg'],
      tags: ['GSAP', 'React', 'Redux'],
      description: 'Redux를 이용한 전역 상태 관리.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 28,
      numViews: 450,
      numLikes: 230,
      reviews: [],
    },
    {
      title: 'Tailwind CSS로 반응형 디자인 적용 및 차이점 이해하기',
      slug: 'tailwind-css로-반응형-디자인',
      category: 'tutorial',
      subCategory: 'GSAP Interative Animation',
      images: ['/images/post-19-1.jpg', '/images/post-19-2.jpg'],
      tags: ['GSAP', 'Tailwind CSS', 'design'],
      description: 'Tailwind CSS의 장점과 활용법.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 20,
      numViews: 340,
      numLikes: 160,
      reviews: [],
    },
    {
      title: 'Rust 언어로 고성능 애플리케이션 개발 및 배포하기',
      slug: 'rust-언어로-고성능-애플리케이션-개발',
      category: 'inspiration',
      subCategory: 'SITE 인스퍼레이션',
      images: ['/images/post-20-1.jpg', '/images/post-20-2.jpg'],
      tags: ['SITE', 'Rust', 'performance'],
      description: 'Rust 언어의 특성과 활용 사례.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 18,
      numViews: 310,
      numLikes: 150,
      reviews: [],
    },
    {
      title: 'Rust 언어로 고성능 애플리케이션 개발하고 삭제하기',
      slug: 'rust-언어로-고성능-애aa플리',
      category: 'lecture',
      subCategory: '웹디자인개발기능사 2025',
      images: ['/images/post-20-1.jpg', '/images/post-20-2.jpg'],
      tags: ['Rust', 'performance'],
      description: 'Rust 언어의 특성과 활용 사례.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 18,
      numViews: 310,
      numLikes: 150,
      reviews: [],
    },
    {
      title: 'Rust 언어로 고성능 애플리케이션 개발하고 삭제하기',
      slug: 'rust-언어로-고성능-애플gg리',
      category: 'lecture',
      subCategory: '리액트를 위한 자바스크립트 기초 마스터',
      images: ['/images/post-10-1.jpg', '/images/post-20-2.jpg'],
      tags: ['Rust', 'performance'],
      description: 'Rust 언어의 특성과 활용 사례.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 18,
      numViews: 310,
      numLikes: 150,
      reviews: [],
    },
    {
      title: 'Git 언어로 고성능 애플리케이션 개발하고 삭제하기',
      slug: 'rust-언어로-고성능-애d플리',
      category: 'lecture',
      subCategory: '리액트를 위한 자바스크립트 기초 마스터',
      images: ['/images/post-10-1.jpg', '/images/post-20-2.jpg'],
      tags: ['Rust', 'performance'],
      description: 'Rust 언어의 특성과 활용 사례.',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 18,
      numViews: 310,
      numLikes: 150,
      reviews: [],
    },
  ],
  users: [
    {
      name: 'John',
      password: bcrypt.hashSync('123456', 10),
      email: 'admin@example.com',
      emailVerified: false,
      image: '/images/face01.jpg',
      role: 'Admin',
      visitCount: 4,
    },
    {
      name: 'Jane Smith',
      password: bcrypt.hashSync('123456', 10),
      email: 'janesmith@example.com',
      emailVerified: false,
      image: '/images/face02.jpg',
      role: 'User',
      visitCount: 5,
    },
    {
      name: 'Alice Johnson',
      password: bcrypt.hashSync('123456', 10),
      email: 'alicej@example.com',
      emailVerified: false,
      image: '/images/face03.jpg',
      role: 'User',
      visitCount: 15,
    },
    {
      name: 'Bob Williams',
      password: bcrypt.hashSync('123456', 10),
      email: 'bobw@example.com',
      emailVerified: false,
      image: '/images/face04.jpg',
      role: 'User',
      visitCount: 8,
    },
    {
      name: 'Charlie Brown',
      password: bcrypt.hashSync('123456', 10),
      email: 'charlieb@example.com',
      emailVerified: false,
      image: '/images/face05.jpg',
      role: 'User',
      visitCount: 12,
    },
    {
      name: 'David Clark',
      password: bcrypt.hashSync('123456', 10),
      email: 'davidc@example.com',
      emailVerified: false,
      image: '/images/face06.jpg',
      role: 'User',
      visitCount: 3,
    },
    {
      name: 'Emma White',
      password: bcrypt.hashSync('123456', 10),
      email: 'emmaw@example.com',
      emailVerified: false,
      image: '/images/face07.jpg',
      role: 'User',
      visitCount: 9,
    },
    {
      name: 'Frank Green',
      password: bcrypt.hashSync('123456', 10),
      email: 'frankg@example.com',
      emailVerified: true,
      image: '/images/face08.jpg',
      role: 'User',
      visitCount: 14,
    },
    {
      name: 'Grace Hall',
      password: bcrypt.hashSync('123456', 10),
      email: 'graceh@example.com',
      emailVerified: false,
      image: '/images/face09.jpg',
      role: 'User',
      visitCount: 6,
    },
    {
      name: 'Henry Young',
      password: bcrypt.hashSync('123456', 10),
      email: 'henryy@example.com',
      emailVerified: true,
      image: '/images/face10.jpg',
      role: 'User',
      visitCount: 7,
    },
    {
      name: 'Isabella Lee',
      password: bcrypt.hashSync('123456', 10),
      email: 'isabellal@example.com',
      emailVerified: false,
      image: '/images/face01.jpg',
      role: 'User',
      visitCount: 11,
    },
    {
      name: 'Jack Wilson',
      password: bcrypt.hashSync('123456', 10),
      email: 'jackw@example.com',
      emailVerified: false,
      image: '/images/face02.jpg',
      role: 'User',
      visitCount: 13,
    },
    {
      name: 'Katherine Adams',
      password: bcrypt.hashSync('123456', 10),
      email: 'katherinea@example.com',
      emailVerified: false,
      image: '/images/face03.jpg',
      role: 'User',
      visitCount: 2,
    },
    {
      name: 'Leo Thomas',
      password: bcrypt.hashSync('123456', 10),
      email: 'leot@example.com',
      emailVerified: true,
      image: '/images/face04.jpg',
      role: 'User',
      visitCount: 4,
    },
    {
      name: 'Mia Scott',
      password: bcrypt.hashSync('123456', 10),
      email: 'mias@example.com',
      emailVerified: false,
      image: '/images/face05.jpg',
      role: 'User',
      visitCount: 16,
    },
    {
      name: 'Nathan Evans',
      password: bcrypt.hashSync('123456', 10),
      email: 'nathane@example.com',
      emailVerified: false,
      image: '/images/face06.jpg',
      role: 'User',
      visitCount: 1,
    },
    {
      name: 'Olivia Harris',
      password: bcrypt.hashSync('123456', 10),
      email: 'oliviah@example.com',
      emailVerified: false,
      image: '/images/face07.jpg',
      role: 'User',
      visitCount: 18,
    },
    {
      name: 'Paul Martin',
      password: bcrypt.hashSync('123456', 10),
      email: 'paulm@example.com',
      emailVerified: false,
      image: '/images/face08.jpg',
      role: 'User',
      visitCount: 17,
    },
    {
      name: 'Quinn Lewis',
      password: bcrypt.hashSync('123456', 10),
      email: 'quinnl@example.com',
      emailVerified: false,
      image: '/images/face09.jpg',
      role: 'User',
      visitCount: 20,
    },
    {
      name: 'Rachel Walker',
      password: bcrypt.hashSync('123456', 10),
      email: 'rachelw@example.com',
      emailVerified: false,
      image: '/images/face01.jpg',
      role: 'User',
      visitCount: 19,
    },
  ],
};

export default data;
